DROP DATABASE IF EXISTS FinalProject;
CREATE DATABASE FinalProject;
USE FinalProject;

CREATE TABLE User (
	userID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    username VARCHAR(40) NOT NULL,
    email VARCHAR(40) NOT NULL,
    password VARCHAR(40) NOT NULL,
    fName VARCHAR(40) NOT NULL,
    lName VARCHAR(40) NOT NULL
);

CREATE TABLE FlashcardSet (
	setID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	userID INT NOT NULL,
    name VARCHAR(40) NOT NULL,
    FOREIGN KEY (userID) REFERENCES User(userID)
);

CREATE TABLE Flashcard (
	flashcardID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    setID INT NOT NULL,
    frontText VARCHAR(500) NOT NULL,
    backText VARCHAR(500) NOT NULL,
    FOREIGN KEY (setID) REFERENCES FlashcardSet(setID)
);